menu:
  前端工程: /engineer/summary/
  数据银行: /access/summary/
  支付革命: /warfare/summary/
  海量服务: /ocean/summary/
  About:    /about/summary/
# rss: /atom.xml

archive_date_format: MMM DD

duoshuo_shortname: ronesam

fork: ronesam/hexo-theme-zero/

cdn:
  #prefix: http://7xo6lp.com1.z0.glb.clouddn.com/static/
  prefix: /static/
  favicon: img/favicon.ico
  fork: img/fork.png
  lib: //cdn.bootcss.com/