menu:
  界面交互（风）: /air/summary/
  表现控制（火）: /fire/summary/
  海量服务（水）: /water/summary/
  数据银行（地）: /earth/summary/
  About:   /about/summary/
# rss: /atom.xml

archive_date_format: MMM DD

duoshuo_shortname: ronesam

#Your github account like: ronesam
fork: ronesam

cdn:
  #prefix: http://7xo6lp.com1.z0.glb.clouddn.com/static/
  prefix: /static/
  #prefix + favicon is real url
  favicon: img/favicon.ico
  #lib: //cdn.bootcss.com/
  lib: /static/